### ISSUE TITLE
error when adding Field constraint

### ISSUE THREAD

**Issue by falkben** [dotX12/pyfa-converter#14]
On:

python: 3.10 and 3.11
pyfa-converter: 1.0.3.0 (and `master`, which shows as 1.0.1.0)
pydantic: 1.10.2

If you add a `Field` constraint, pydantic raises a ValueError:

For example, for the class in this repo, if you change it to (adding a `gt` constraint of `10`:

```python
class PostContractSmallDoubleBodySchema(BaseModel):
    id: Optional[int] = Field(None, description="gwa", gt=10)
    title: Optional[str] = Field(None)
    data: Optional[List[int]]
```

pydantic raises the following exception

```
ImportError while loading conftest '/home/ben/repos/pyfa-converter/tests/conftest.py'.
tests/conftest.py:6: in <module>
    from examples.main import app
examples/main.py:47: in <module>
    @app.post("/test")
.venv/lib/python3.11/site-packages/fastapi/routing.py:630: in decorator
    self.add_api_route(
.venv/lib/python3.11/site-packages/fastapi/routing.py:569: in add_api_route
    route = route_class(
.venv/lib/python3.11/site-packages/fastapi/routing.py:438: in __init__
    self.dependant = get_dependant(path=self.path_format, call=self.endpoint)
.venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py:292: in get_dependant
    sub_dependant = get_param_sub_dependant(
.venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py:122: in get_param_sub_dependant
    return get_sub_dependant(
.venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py:158: in get_sub_dependant
    sub_dependant = get_dependant(
.venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py:299: in get_dependant
    param_field = get_param_field(
.venv/lib/python3.11/site-packages/fastapi/dependencies/utils.py:388: in get_param_field
    annotation = get_annotation_from_field_info(annotation, field_info, param_name)
pydantic/schema.py:1011: in pydantic.schema.get_annotation_from_field_info
    ???
E   ValueError: On field "id" the following field constraints are set but not enforced: gt.
E   For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

I spent some time investigating and I'm still not sure why this is happening

**Comment by dotX12** [comment]
@falkben, sorry for the long reply, busy with work :(
I'll fix it this weekend!

**Comment by dotX12** [comment]
I see a problem but I can't figure out how to solve it...

I can suggest a workaround that surprisingly works :)
```python3
from pydantic import conint
id: conint(gt=10) = Field(..., description="gwa")
```

**Comment by dotX12** [comment]
> I see a problem but I can't figure out how to solve it...
> 
> I can suggest a workaround that surprisingly works :)
> 
> ```python
> from pydantic import conint
> id: conint(gt=10) = Field(..., description="gwa")
> ```

@falkben

**Comment by dotX12** [comment]
```sh
curl -X 'POST' \
  'http://127.0.0.1:8000/register' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'id=5'
```

```json
{
  "detail": [
    {
      "loc": [
        "body",
        "id"
      ],
      "msg": "ensure this value is greater than 10",
      "type": "value_error.number.not_gt",
      "ctx": {
        "limit_value": 10
      }
    }
  ]
}

```

**Comment by dotX12** [comment]
UPD


```python3
from pydantic import BaseModel
from pydantic import ConstrainedInt
from pydantic import Field


class Model(BaseModel):
    foo: ConstrainedInt = Field(..., ge=10)


print(Model(foo=10))

```

```python3
Traceback (most recent call last):
  File "C:\Users\dotX12\Documents\PycharmProjects\pydantic-to-fastapi\test.py", line 6, in <module>
    class Model(BaseModel):
  File "pydantic\main.py", line 198, in pydantic.main.ModelMetaclass.__new__
  File "pydantic\fields.py", line 504, in pydantic.fields.ModelField.infer
  File "pydantic\schema.py", line 1011, in pydantic.schema.get_annotation_from_field_info
ValueError: On field "foo" the following field constraints are set but not enforced: ge. 
For more details see https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints
```

I figured out the reason, it's a pydantic mechanic :)
https://pydantic-docs.helpmanual.io/usage/schema/#unenforced-field-constraints

Due to double conversion, pydantic-form-pydantic int becomes ConstrainedInt

```python3
@classmethod
def __fill_params(
    cls, param: Callable[..., FieldInfo], model_field: ModelField, default: Any
) -> FieldInfo:
    print(model_field.annotation)
```
```python3
<class '__main__.ConstrainedIntValue'>
typing.Optional[str]
typing.Optional[typing.List[int]]
```

**Comment by dotX12** [comment]
```python3
class PostContractSmallDoubleBodySchema(BaseModel):
    id: int = Field(..., description="gwa", ge=10)
    title: Optional[str] = Field(None)
    data: Optional[List[int]]


print(list(PostContractSmallDoubleBodySchema.__fields__.values())[0].annotation)
<class '__main__.ConstrainedIntValue'>
```

its fine :D

**Comment by dotX12** [comment]
I have an idea how to get rid of the pydantic annotation override. I'm going to try now.

**Comment by dotX12** [comment]
Your example works if you do
```python3
annotation=model.__annotations__.get(field.name)
```
but the optional typing stops working.

```python3
annotation=model.__annotations__.get(field.name) or field.annotation,
```
works, but it's magical crap, so if something breaks, I returned it as it was.

**Comment by dotX12** [comment]
Release alpha: https://pypi.org/project/pyfa-converter/1.0.4.0a0/
